ALTER TABLE lab_bills
	ADD COLUMN IF NOT EXISTS bill_no BIGSERIAL UNIQUE NOT NULL,
	ADD COLUMN IF NOT EXISTS referred_by TEXT,
	ADD COLUMN IF NOT EXISTS hospital_name TEXT,
	ADD COLUMN IF NOT EXISTS received_amount NUMERIC(12,2) DEFAULT 0,
	ADD COLUMN IF NOT EXISTS balance_amount NUMERIC(12,2) DEFAULT 0,
	ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'Pending';
